// Code generated by MockGen. DO NOT EDIT.
// Source: signup_confirm.go
//
// Generated by this command:
//
//	mockgen -source=signup_confirm.go -destination=../tests/mock/usecase/mock_signup_confirm.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignUpConfirmUseCase is a mock of SignUpConfirmUseCase interface.
type MockSignUpConfirmUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpConfirmUseCaseMockRecorder
	isgomock struct{}
}

// MockSignUpConfirmUseCaseMockRecorder is the mock recorder for MockSignUpConfirmUseCase.
type MockSignUpConfirmUseCaseMockRecorder struct {
	mock *MockSignUpConfirmUseCase
}

// NewMockSignUpConfirmUseCase creates a new mock instance.
func NewMockSignUpConfirmUseCase(ctrl *gomock.Controller) *MockSignUpConfirmUseCase {
	mock := &MockSignUpConfirmUseCase{ctrl: ctrl}
	mock.recorder = &MockSignUpConfirmUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpConfirmUseCase) EXPECT() *MockSignUpConfirmUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSignUpConfirmUseCase) Execute(ctx context.Context, email, confirmationCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, email, confirmationCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSignUpConfirmUseCaseMockRecorder) Execute(ctx, email, confirmationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSignUpConfirmUseCase)(nil).Execute), ctx, email, confirmationCode)
}
