name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run golang test
    runs-on: ubuntu-latest

    env:
      TEST_DB_HOST: localhost
      DB_PORT: 5432
      TEST_DB_USER: postgres
      TEST_DB_PASSWORD: postgres
      TEST_DB_NAME: postgres

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: ${{ env.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.TEST_DB_PASSWORD }}
          POSTGRES_DB: ${{ env.TESt_DB_NAME }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod download
      - name: Run test
        run: go test ./...
    